### ISSUE TITLE
Add Doctrine Cache support

### ISSUE THREAD

**Issue by stloyd** [KnpLabs/KnpDisqusBundle#28]
https://github.com/doctrine/cache

**Comment by DarekTw** [comment]
KnpZendCacheBundle is no longer maintained, I wonder if we could do just a simple replacement
from 'knp_zend_cache.manager' to 'cache' with fetch and save method in Disqus.php

http://doctrine-orm.readthedocs.org/en/latest/reference/caching.html

**Comment by weaverryan** [comment]
@DarekTw I'd welcome a PR about that :). None of us are actively working on this bundle (I use it, but I'm not working on it much).

Cheers!
