### ISSUE TITLE
Replace hardcoded Zend caching layer with PSR-6 compatible

### ISSUE THREAD

**Issue by bocharsky-bw** [KnpLabs/KnpDisqusBundle#43]
In this case, we can use any caching library which implements PSR-6 interfaces: Symfony Cache, Doctrine Cache, etc.

**Comment by sadikoff** [comment]
It can be closed =) latest version allows us to use service decoration and inject whatever caching layer we need =)

**Comment by bocharsky-bw** [comment]
perfect, thanks! :)
