### ISSUE TITLE
Any plans to support sf4?

### ISSUE THREAD

**Issue by sauls** [KnpLabs/KnpDisqusBundle#48]

**Comment by yann-eugone** [comment]
I'm also interested in that support.
I can work on a Pull Request, but I'd like to know if anyone has a todo list for it ?

**Comment by weaverryan** [comment]
Please do open a PR! I would be happy to review and merge it :)

**Comment by yann-eugone** [comment]
I'll try to find some time to work on it this week.
@weaverryan do you already know if there is something that prevent this bundle from being compatible Symfony >= 4.0 ?

**Comment by weaverryan** [comment]
Nothing I know of. But the biggest thing usually is to add public=true on any services that are historically meant to be fetched publicly.

**Comment by BorisCharriere** [comment]
I opened a Pull request for some modification

**Comment by garak** [comment]
I guess this issue can be closed.
Or (even better), its title can be changed to _Any plans to support sf5?_

**Comment by sadikoff** [comment]
So this one truly can be closed latest version should work on symfony ^4.4/^5.0
